/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Boleto.Form.CartaoPonto;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.DAO.FeriadosBrasilDAO;
import model.DAO.funcionario.FuncionarioDAO;
import model.bean.FeriadosBrasil;
import model.bean.Funcionario;

/**
 *
 * @author Jonathan CR
 */
public class frmLancarCartaoPonto21 extends javax.swing.JFrame {

    private Funcionario funcionario;
    private SpinnerNumberModel dia_spinner;
    private DefaultTableModel tb;
    private String jornadaString;
    private int reg = 0, reg_sub = 0;
    private List<FeriadosBrasil> feriados;
    private final DefaultListModel lista_feriados = new DefaultListModel();
    private JFormattedTextField[] horarios;

    private long horas_extra_50, horas_extra_100, horas_faltas, horas_noturnas;
    private final int COLUNA_HORAS_TRABALHADAS = 7;
    private final String CONST_FERIADO = "H";
    private final String CONST_FALTA = "F";
    private final int COLUNA_SAIDA_3 = 6;
    private final int COLUNA_SAIDA_2 = 4;
    private final int COLUNA_SAIDA_1 = 2;

    /**
     * Creates new form frmLancarCartao2
     *
     * @param funcionario
     */
    public frmLancarCartaoPonto21(Funcionario funcionario) {
        initComponents();
        horarios = new JFormattedTextField[6];
        horarios[0] = txt_entrada;
        horarios[1] = txt_saida_intervalo;
        horarios[2] = txt_entrada_intervalo;
        horarios[3] = txt_saida;
        horarios[4] = txt_entrada_aux;
        horarios[5] = txt_saida_aux;
        init(funcionario);
    }

    public void init(Funcionario funcionario_) {
        //defini o funcionario
        funcionario = funcionario_;
        nomeLbl.setText(funcionario.getNome());
        txt_salario_base.setValue(funcionario.getSalario());
        //defini parametros iniciais de controle
        feriados = new ArrayList<>();
        jList1.setModel(lista_feriados);
        reg = -1;
        reg_sub = -1;
        //seta tabela
        tb = (DefaultTableModel) jTable1.getModel();
        //seta data atual
        Calendar calendario = Calendar.getInstance();
        calendario.add(Calendar.MONTH, - 1);
        mes_slider.setValue(calendario.get(Calendar.MONTH) + 1);
        ano_spinner.setValue(calendario.get(Calendar.YEAR));
        //seta variaveis slider e spinner
        dia_spinner = (SpinnerNumberModel) jSpinnerDia.getModel();
        dia_spinner.setValue(1);
        //defini foco
        txt_entrada.requestFocus();
        //grupo de botoes de jornada
        buttonGroup1.add(jornada6);
        buttonGroup1.add(jornada7);
        buttonGroup1.add(jornada5);
        //seta jornada
        jornada7.setSelected(true);
        jornadaString = "07:20";
        alterar_mes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ano_spinner = new javax.swing.JSpinner();
        mes_slider = new javax.swing.JSlider();
        mestxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_entrada = new javax.swing.JFormattedTextField();
        txt_saida_intervalo = new javax.swing.JFormattedTextField();
        txt_entrada_intervalo = new javax.swing.JFormattedTextField();
        txt_saida = new javax.swing.JFormattedTextField();
        txt_entrada_aux = new javax.swing.JFormattedTextField();
        txt_saida_aux = new javax.swing.JFormattedTextField();
        jSpinnerDia = new javax.swing.JSpinner();
        sabadoBtn = new javax.swing.JButton();
        domingoBtn = new javax.swing.JButton();
        folgaBtn = new javax.swing.JButton();
        feriadoBtn = new javax.swing.JButton();
        atestadoBtn = new javax.swing.JButton();
        faltaBtn = new javax.swing.JButton();
        limpaDiaBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jornada6 = new javax.swing.JRadioButton();
        jornada7 = new javax.swing.JRadioButton();
        jornada5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        nomeLbl = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_horas_extras_50 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_horas_faltas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_horas_noturnas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_reducao_noturno = new javax.swing.JTextField();
        txt_horas_extras_100 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_valor_hora = new javax.swing.JTextField();
        txt_valor_hora_extra = new javax.swing.JTextField();
        txt_valor_total_Salario = new javax.swing.JTextField();
        txt_valor_total_Extra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_valor_DSR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_INSS = new javax.swing.JTextField();
        txt_hora_DSR = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_numero_feriados = new javax.swing.JSpinner();
        jButton10 = new javax.swing.JButton();
        inssSpin = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        txt_salario_base = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        txt_descontos = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        txt_indenizacao = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        concluirBtn = new javax.swing.JButton();
        imprimirBtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        importBtn = new javax.swing.JButton();
        fakebtn = new javax.swing.JButton();
        importBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cartão Ponto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ano_spinner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ano_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ano_spinnerStateChanged(evt);
            }
        });

        mes_slider.setBackground(new java.awt.Color(153, 153, 153));
        mes_slider.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        mes_slider.setForeground(new java.awt.Color(0, 0, 0));
        mes_slider.setMajorTickSpacing(1);
        mes_slider.setMaximum(12);
        mes_slider.setMinimum(1);
        mes_slider.setMinorTickSpacing(1);
        mes_slider.setPaintLabels(true);
        mes_slider.setPaintTicks(true);
        mes_slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mes_sliderMouseClicked(evt);
            }
        });
        mes_slider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mes_sliderKeyPressed(evt);
            }
        });

        mestxt.setText("Mes");

        jLabel1.setText("Ano");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mes_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(ano_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(mestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mestxt)
                    .addComponent(jLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(mes_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ano_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Entrada", "S. Intervalo", "E. Intervalo", "Saida", "Entrada", "Saida", "Horas Trabalhadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        try {
            txt_entrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_entrada.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_entradaKeyPressed(evt);
            }
        });

        try {
            txt_saida_intervalo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_saida_intervalo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_saida_intervalo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_saida_intervaloKeyPressed(evt);
            }
        });

        try {
            txt_entrada_intervalo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_entrada_intervalo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_entrada_intervalo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_entrada_intervaloKeyPressed(evt);
            }
        });

        try {
            txt_saida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_saida.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saidaActionPerformed(evt);
            }
        });
        txt_saida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_saidaKeyPressed(evt);
            }
        });

        try {
            txt_entrada_aux.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_entrada_aux.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_entrada_aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_entrada_auxKeyPressed(evt);
            }
        });

        try {
            txt_saida_aux.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_saida_aux.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txt_saida_aux.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_saida_auxKeyPressed(evt);
            }
        });

        jSpinnerDia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerDiaStateChanged(evt);
            }
        });

        sabadoBtn.setText("S: Sábado");
        sabadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabadoBtnActionPerformed(evt);
            }
        });

        domingoBtn.setText("D: Domingo");
        domingoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domingoBtnActionPerformed(evt);
            }
        });

        folgaBtn.setText("R: Folga");
        folgaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folgaBtnActionPerformed(evt);
            }
        });

        feriadoBtn.setText("H: Feriado");
        feriadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feriadoBtnActionPerformed(evt);
            }
        });

        atestadoBtn.setText("A: Atestado");
        atestadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atestadoBtnActionPerformed(evt);
            }
        });

        faltaBtn.setText("F: Falta");
        faltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faltaBtnActionPerformed(evt);
            }
        });

        limpaDiaBtn.setText("Limpar Dia");
        limpaDiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaDiaBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Jornada"));

        jornada6.setBackground(new java.awt.Color(255, 255, 255));
        jornada6.setText("06:00");
        jornada6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jornada6MouseClicked(evt);
            }
        });
        jornada6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada6ActionPerformed(evt);
            }
        });

        jornada7.setBackground(new java.awt.Color(255, 255, 255));
        jornada7.setText("07:20");
        jornada7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada7ActionPerformed(evt);
            }
        });

        jornada5.setBackground(new java.awt.Color(255, 255, 255));
        jornada5.setText("05:20");
        jornada5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jornada5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jornada7)
                    .addComponent(jornada5)
                    .addComponent(jornada6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jornada5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jornada6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jornada7))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Estatística", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        nomeLbl.setEditable(false);
        nomeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeLbl.setFocusable(false);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Calculo Folha"));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Horas Extras 50%");

        txt_horas_extras_50.setEditable(false);
        txt_horas_extras_50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Horas Faltas");

        txt_horas_faltas.setEditable(false);
        txt_horas_faltas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Horas Noturnas");

        txt_horas_noturnas.setEditable(false);
        txt_horas_noturnas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Redução Horas Noturno");

        txt_reducao_noturno.setEditable(false);
        txt_reducao_noturno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txt_horas_extras_100.setEditable(false);
        txt_horas_extras_100.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Horas Extras 100%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_horas_faltas)
            .addComponent(txt_horas_noturnas)
            .addComponent(txt_reducao_noturno)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txt_horas_extras_50))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txt_horas_extras_100))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(txt_horas_extras_50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addComponent(txt_horas_extras_100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(txt_horas_faltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(txt_horas_noturnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(txt_reducao_noturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Calculo Aproximado"));

        jLabel7.setText("Salário Base");

        jLabel8.setText("Valor Hora");

        jLabel9.setText("Valor H. Extra");

        jLabel10.setText("Valor Total");

        jLabel11.setText("Total Extra");

        jLabel12.setText("Total DSR");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("INSS");

        jLabel13.setText("Nº Feriados");

        txt_numero_feriados.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton10.setText("Calcular");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        inssSpin.setModel(new javax.swing.SpinnerNumberModel(9, 0, null, 1));

        jLabel15.setText("%");

        txt_salario_base.setModel(new javax.swing.SpinnerNumberModel(1323.0d, 0.0d, null, 1.0d));

        jLabel16.setText("Descontos");

        txt_descontos.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel17.setText("Hora DSR");

        txt_indenizacao.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel18.setText("Indenização");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_valor_total_Salario)
            .addComponent(txt_valor_total_Extra)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(inssSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_INSS))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hora_DSR)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_valor_DSR, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(txt_valor_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_valor_hora_extra))
            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_salario_base, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_descontos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txt_numero_feriados))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_indenizacao)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_salario_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numero_feriados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_indenizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valor_hora_extra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valor_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_INSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inssSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valor_DSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hora_DSR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(txt_valor_total_Extra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(txt_valor_total_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel7);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Feriados"));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeLbl)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane4)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(nomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        concluirBtn.setText("Concluir");
        concluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirBtnActionPerformed(evt);
            }
        });

        imprimirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/printer.png"))); // NOI18N
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });

        editbtn.setText("Editar");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Dia Corrente");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        importBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white_picture.png"))); // NOI18N
        importBtn.setToolTipText("Importar CVS");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        fakebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white_code.png"))); // NOI18N
        fakebtn.setToolTipText("Cartão Fictício");
        fakebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakebtnActionPerformed(evt);
            }
        });

        importBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white_code_red.png"))); // NOI18N
        importBtn1.setToolTipText("Diminuir Diferença de Horas");
        importBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSpinnerDia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_saida_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txt_entrada_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txt_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_entrada_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_saida_aux, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(limpaDiaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domingoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sabadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(fakebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(importBtn))
                                    .addComponent(importBtn1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(folgaBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feriadoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(atestadoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faltaBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(concluirBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerDia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_entrada)
                                        .addComponent(txt_saida_intervalo)
                                        .addComponent(txt_entrada_intervalo)
                                        .addComponent(txt_saida)
                                        .addComponent(txt_entrada_aux)
                                        .addComponent(txt_saida_aux)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(importBtn)
                                    .addComponent(fakebtn))
                                .addGap(5, 5, 5)
                                .addComponent(importBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sabadoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(domingoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(folgaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(feriadoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atestadoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(faltaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limpaDiaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imprimirBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(concluirBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ano_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ano_spinnerStateChanged
        alterar_dias();
    }//GEN-LAST:event_ano_spinnerStateChanged

    private void txt_entradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entradaKeyPressed

    }//GEN-LAST:event_txt_entradaKeyPressed

    private void txt_saida_intervaloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_saida_intervaloKeyPressed

    }//GEN-LAST:event_txt_saida_intervaloKeyPressed

    private void txt_entrada_intervaloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entrada_intervaloKeyPressed

    }//GEN-LAST:event_txt_entrada_intervaloKeyPressed

    private void txt_saidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_saidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (lancar_dia()) {
                calcular_horas();
            }
        }
    }//GEN-LAST:event_txt_saidaKeyPressed

    private void txt_entrada_auxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entrada_auxKeyPressed

    }//GEN-LAST:event_txt_entrada_auxKeyPressed

    private void txt_saida_auxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_saida_auxKeyPressed

    }//GEN-LAST:event_txt_saida_auxKeyPressed

    private void jSpinnerDiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerDiaStateChanged

    }//GEN-LAST:event_jSpinnerDiaStateChanged

    private void sabadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabadoBtnActionPerformed

    }//GEN-LAST:event_sabadoBtnActionPerformed

    private void domingoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domingoBtnActionPerformed

    }//GEN-LAST:event_domingoBtnActionPerformed

    private void folgaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folgaBtnActionPerformed

    }//GEN-LAST:event_folgaBtnActionPerformed

    private void feriadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feriadoBtnActionPerformed
        jTable1.setValueAt("H", 0, 0);
    }//GEN-LAST:event_feriadoBtnActionPerformed

    private void atestadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atestadoBtnActionPerformed

    }//GEN-LAST:event_atestadoBtnActionPerformed

    private void faltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faltaBtnActionPerformed

    }//GEN-LAST:event_faltaBtnActionPerformed

    private void limpaDiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaDiaBtnActionPerformed

    }//GEN-LAST:event_limpaDiaBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jornada6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jornada6MouseClicked
    }//GEN-LAST:event_jornada6MouseClicked

    private void jornada7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada7ActionPerformed

    }//GEN-LAST:event_jornada7ActionPerformed

    private void jornada6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada6ActionPerformed

    }//GEN-LAST:event_jornada6ActionPerformed

    private void txt_saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saidaActionPerformed
    }//GEN-LAST:event_txt_saidaActionPerformed

    private void concluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirBtnActionPerformed

    }//GEN-LAST:event_concluirBtnActionPerformed

    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed

    }//GEN-LAST:event_imprimirBtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed

    }//GEN-LAST:event_editbtnActionPerformed

    private void jornada5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jornada5ActionPerformed

    }//GEN-LAST:event_jornada5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

    }//GEN-LAST:event_jButton10ActionPerformed

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed

    }//GEN-LAST:event_importBtnActionPerformed

    private void fakebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakebtnActionPerformed

    }//GEN-LAST:event_fakebtnActionPerformed

    private void importBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtn1ActionPerformed

    }//GEN-LAST:event_importBtn1ActionPerformed

    private void mes_sliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mes_sliderMouseClicked
        alterar_mes();
        alterar_dias();
    }//GEN-LAST:event_mes_sliderMouseClicked

    private void mes_sliderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mes_sliderKeyPressed
        alterar_mes();
        alterar_dias();
    }//GEN-LAST:event_mes_sliderKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLancarCartaoPonto21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLancarCartaoPonto21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLancarCartaoPonto21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLancarCartaoPonto21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLancarCartaoPonto21(new FuncionarioDAO().getFuncionario(2)).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ano_spinner;
    private javax.swing.JButton atestadoBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton concluirBtn;
    private javax.swing.JButton domingoBtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton fakebtn;
    private javax.swing.JButton faltaBtn;
    private javax.swing.JButton feriadoBtn;
    private javax.swing.JButton folgaBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JButton importBtn1;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JSpinner inssSpin;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerDia;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jornada5;
    private javax.swing.JRadioButton jornada6;
    private javax.swing.JRadioButton jornada7;
    private javax.swing.JButton limpaDiaBtn;
    private javax.swing.JSlider mes_slider;
    private javax.swing.JLabel mestxt;
    private javax.swing.JTextField nomeLbl;
    private javax.swing.JButton sabadoBtn;
    private javax.swing.JTextField txt_INSS;
    private javax.swing.JSpinner txt_descontos;
    private javax.swing.JFormattedTextField txt_entrada;
    private javax.swing.JFormattedTextField txt_entrada_aux;
    private javax.swing.JFormattedTextField txt_entrada_intervalo;
    private javax.swing.JTextField txt_hora_DSR;
    private javax.swing.JTextField txt_horas_extras_100;
    private javax.swing.JTextField txt_horas_extras_50;
    private javax.swing.JTextField txt_horas_faltas;
    private javax.swing.JTextField txt_horas_noturnas;
    private javax.swing.JSpinner txt_indenizacao;
    private javax.swing.JSpinner txt_numero_feriados;
    private javax.swing.JTextField txt_reducao_noturno;
    private javax.swing.JFormattedTextField txt_saida;
    private javax.swing.JFormattedTextField txt_saida_aux;
    private javax.swing.JFormattedTextField txt_saida_intervalo;
    private javax.swing.JSpinner txt_salario_base;
    private javax.swing.JTextField txt_valor_DSR;
    private javax.swing.JTextField txt_valor_hora;
    private javax.swing.JTextField txt_valor_hora_extra;
    private javax.swing.JTextField txt_valor_total_Extra;
    private javax.swing.JTextField txt_valor_total_Salario;
    // End of variables declaration//GEN-END:variables

    private void alterar_mes() {
        lista_feriados.removeAllElements();
        feriados = new FeriadosBrasilDAO().getFeriadosDoMes(mes_slider.getValue(), (int) ano_spinner.getValue());
        lista_feriados.addAll(feriados);
        switch (mes_slider.getValue()) {
            case 1:
                mestxt.setText("Janeiro");
                break;
            case 2:
                mestxt.setText("Fevereiro");
                break;
            case 3:
                mestxt.setText("Março");
                break;
            case 4:
                mestxt.setText("Abril");
                break;
            case 5:
                mestxt.setText("Maio");
                break;
            case 6:
                mestxt.setText("Junho");
                break;
            case 7:
                mestxt.setText("Julho");
                break;
            case 8:
                mestxt.setText("Agosto");
                break;
            case 9:
                mestxt.setText("Setembro");
                break;
            case 10:
                mestxt.setText("Outubro");
                break;
            case 11:
                mestxt.setText("Novembro");
                break;
            case 12:
                mestxt.setText("Dezembro");
                break;
        }
    }

    private void alterar_dias() {
        Calendar calendario = Calendar.getInstance();
        calendario.set(Calendar.YEAR, (int) ano_spinner.getValue());
        calendario.set(Calendar.MONTH, mes_slider.getValue() - 1);
        int ultimo_dia_mes = calendario.getActualMaximum(Calendar.DAY_OF_MONTH);
        tb.setRowCount(ultimo_dia_mes);
        for (int dia = 1; dia < ultimo_dia_mes + 1; dia++) {
            calendario.set(Calendar.DAY_OF_MONTH, dia);
            if (calendario.get(Calendar.DAY_OF_WEEK) == 1) { //se for domingo
                tb.setValueAt("D", dia - 1, 0);
            } else {
                tb.setValueAt(dia, dia - 1, 0);
            }
        }
    }

    private boolean lancar_dia() {
        for (int x = 0; x < horarios.length; x++) {
            boolean test = hora_valida(horarios[x].getText());
            if (test) {
                if (horarios[x].getText().equals("  :  ")) {
                    jTable1.setValueAt(null, ((int) dia_spinner.getValue() - 1), x + 1);
                } else {
                    jTable1.setValueAt(horarios[x].getText(), ((int) dia_spinner.getValue() - 1), x + 1);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algum valor esta errado.");
                return false;
            }
        }
        dia_spinner.setValue((int) dia_spinner.getValue() + 1);
        return true;
    }

    private boolean hora_valida(String test) {
        if (test.equals("  :  ")) {
            return true;
        }
        String[] time = test.split(":");
        try {
            Calendar calendario = Calendar.getInstance();
            calendario.set(Calendar.HOUR_OF_DAY, Integer.parseInt(time[0]));
            calendario.set(Calendar.MINUTE, Integer.parseInt(time[1]));
            return true;
        } catch (NumberFormatException e) {
            System.err.println(e);
            return false;
        }
    }

    private void calcular_horas() {
        horas_extra_50 = 0;
        horas_extra_100 = 0;
        horas_faltas = 0;
        horas_noturnas = 0;
        Calendar[] time;

        for (int index = 0; index < jTable1.getRowCount(); index++) {
            //obtem todos os tempos
            time = obterTimeLinhaJTable(index);
            //obtem as horas trabalhadas em miles
            Long horas_trab_miles = horas_trabalhadas_miles(time);
            //seta jtable
            jTable1.setValueAt(milesToHoraString(horas_trab_miles), index, COLUNA_HORAS_TRABALHADAS);

            Calendar horas_trabalhadas = milesToCalendar(horas_trab_miles);

            //Horas extras
            if (horas_trabalhadas.after(getJornadaCalendar())) {

                //Horas Extras noturnas
                Calendar ultimo_time_22 = Calendar.getInstance();
                Calendar primeiro_time_5 = Calendar.getInstance();
                ultimo_time_22.set(Calendar.HOUR_OF_DAY, 22);
                primeiro_time_5.set(Calendar.HOUR_OF_DAY, 5);
                ultimo_time_22.set(Calendar.MINUTE, 0);
                primeiro_time_5.set(Calendar.MINUTE, 0);
                ultimo_time_22.set(Calendar.SECOND, 0);
                primeiro_time_5.set(Calendar.SECOND, 0);
                primeiro_time_5.add(Calendar.DAY_OF_YEAR, 1);
                long hor_noturno_miles = 0;
                if (jTable1.getValueAt(index, COLUNA_SAIDA_3) != null) {
                    if (time[5].after(ultimo_time_22) && time[5].before(primeiro_time_5)) {
                        hor_noturno_miles = time[5].getTimeInMillis() - ultimo_time_22.getTimeInMillis();
                    }
                } else if (jTable1.getValueAt(index, COLUNA_SAIDA_2) != null) {
                    if (time[3].after(ultimo_time_22) && time[3].before(primeiro_time_5)) {
                        hor_noturno_miles = time[3].getTimeInMillis() - ultimo_time_22.getTimeInMillis();
                    }
                } else if (jTable1.getValueAt(index, COLUNA_SAIDA_1) != null) {
                    if (time[1].after(ultimo_time_22) && time[1].before(primeiro_time_5)) {
                        hor_noturno_miles = time[1].getTimeInMillis() - ultimo_time_22.getTimeInMillis();
                    }
                }

                //se linha atual for marcado como Feriado entao hora extra de 100%
                if (String.valueOf(jTable1.getValueAt(index, 0)).equals(CONST_FERIADO)) {
                    horas_extra_100 += (horas_trabalhadas.getTimeInMillis() - getJornadaCalendar().getTimeInMillis()) - hor_noturno_miles;
                    txt_horas_extras_100.setText(milesToHoraString(horas_extra_100));
                } else {
                    horas_extra_50 += (horas_trabalhadas.getTimeInMillis() - getJornadaCalendar().getTimeInMillis()) - hor_noturno_miles;
                    txt_horas_extras_50.setText(milesToHoraString(horas_extra_50));
                }
                if (hor_noturno_miles > 0) {
                    horas_noturnas += hor_noturno_miles;
                    txt_horas_noturnas.setText(milesToHoraString(horas_noturnas));
                }

            } //Horas Faltas
            else if (horas_trabalhadas.before(getJornadaCalendar())) {
                //HORAS Faltas só contabiliza se no cartão o dia for FALTA ou tiver mais de 1 minuto trabalhado no dia
                if (String.valueOf(jTable1.getValueAt(index, 0)).equals(CONST_FALTA)
                        || horas_trab_miles > 60000) {
                    System.out.println(horas_trab_miles);
                    horas_faltas += getJornadaCalendar().getTimeInMillis() - horas_trabalhadas.getTimeInMillis();
                    txt_horas_faltas.setText(milesToHoraString(horas_faltas));
                }
            }
            
        }
    }

    private Calendar[] obterTimeLinhaJTable(int index) {
        Calendar[] time = new Calendar[horarios.length];
        for (int x = 0; x < time.length; x++) {
            time[x] = Calendar.getInstance();
            String time_string;
            String[] split_time;
            if (jTable1.getValueAt(index, x + 1) != null) {
                time_string = (String) jTable1.getValueAt(index, x + 1);
                split_time = time_string.split(":");
            } else {
                split_time = "00:00".split(":");
            }
            time[x].set(Calendar.HOUR_OF_DAY, 0);
            time[x].set(Calendar.MINUTE, 0);
            time[x].set(Calendar.SECOND, 0);
            //se a pessoa colocar 25 HORAS o calendar passa para o proximo dia
            time[x].add(Calendar.HOUR_OF_DAY, Integer.parseInt(split_time[0]));
            time[x].add(Calendar.MINUTE, Integer.parseInt(split_time[1]));
            /*
            time[x].set(Calendar.HOUR_OF_DAY, Integer.parseInt(split_time[0]));
            time[x].set(Calendar.MINUTE, Integer.parseInt(split_time[1]));
            time[x].set(Calendar.SECOND, 0);
             */
        }
        return time;
    }

    private long horas_trabalhadas_miles(Calendar[] time) {
        Long entradas_miles = time[0].getTimeInMillis() + time[2].getTimeInMillis() + time[4].getTimeInMillis();
        Long saidas_miles = time[1].getTimeInMillis() + time[3].getTimeInMillis() + time[5].getTimeInMillis();
        return saidas_miles - entradas_miles;
    }

    private String calendarToHorasString(Calendar horas_calendar) {
        String hour = horas_calendar.get(Calendar.HOUR_OF_DAY) >= 10 ? Integer.toString(horas_calendar.get(Calendar.HOUR_OF_DAY)) : "0" + Integer.toString(horas_calendar.get(Calendar.HOUR_OF_DAY));
        String min = horas_calendar.get(Calendar.MINUTE) >= 10 ? Integer.toString(horas_calendar.get(Calendar.MINUTE)) : "0" + Integer.toString(horas_calendar.get(Calendar.MINUTE));
        return hour + ":" + min;
    }

    private Calendar getJornadaCalendar() {
        String[] jornada_split = jornadaString.split(":");
        Calendar jornada_calendar = Calendar.getInstance();
        jornada_calendar.set(Calendar.HOUR_OF_DAY, Integer.parseInt(jornada_split[0]));
        jornada_calendar.set(Calendar.MINUTE, Integer.parseInt(jornada_split[1]));
        jornada_calendar.set(Calendar.SECOND, 0);
        return jornada_calendar;
    }

    private String milesToHoraString(Long miles) {
        Calendar calendario = Calendar.getInstance();
        /*
            Caso a quantidade de tempo ultrapasse 1 Dia, então deve retornar com o valor total somado:
            Ex: 25:00, 72:00....
         */
        int controle_dia = calendario.get(Calendar.DAY_OF_YEAR);
        calendario.set(Calendar.HOUR_OF_DAY, 0);
        calendario.set(Calendar.MINUTE, 0);
        calendario.set(Calendar.SECOND, 0);
        calendario.setTimeInMillis(calendario.getTimeInMillis() + miles);
        if (calendario.get(Calendar.DAY_OF_YEAR) > controle_dia) {
            String[] hour_temp = calendarToHorasString(calendario).split(":");
            hour_temp[0] = Integer.toString(24 * (calendario.get(Calendar.DAY_OF_YEAR) - controle_dia) + Integer.parseInt(hour_temp[0]));
            return hour_temp[0] + ":" + hour_temp[1];
        }
        return calendarToHorasString(calendario);
    }

    private Calendar milesToCalendar(Long miles) {
        Calendar calendario = Calendar.getInstance();
        calendario.set(Calendar.HOUR_OF_DAY, 0);
        calendario.set(Calendar.MINUTE, 0);
        calendario.set(Calendar.SECOND, 0);
        calendario.setTimeInMillis(calendario.getTimeInMillis() + miles);
        return calendario;
    }
}
