/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Boleto.Form;

import funcoes.AutoCompletion;
import funcoes.CDate;
import funcoes.CDbl;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.BoletoDAO;
import model.DAO.FornecedorDAO;
import model.bean.Boleto;
import model.bean.Fornecedor;

/**
 *
 * @author User
 */
public class BoletoFrm extends javax.swing.JInternalFrame {
    
    private int banco;

    /**
     * Creates new form TelaBoletoVisualizar
     */
    public BoletoFrm() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
        atualizarValorTotalAberto();
        AutoCompletion.enable(jComboBoxFornecedor);
        jButton1ActionPerformed(null);
    }
    
    private String DataMySQLtoDataStringPT(String data_) {
        DateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date data = null;
        try {
            data = (Date) f.parse(data_);
        } catch (ParseException ex) {
            System.err.println("Erro ao converter data :" + ex);
        }
        String temp2 = sdf.format(data);
        return temp2;
    }
    
    private void pagar(int id, int index) {
        try {
            Boleto b = new Boleto();
            b.setId(id);
            SimpleDateFormat databr = new SimpleDateFormat("dd/MM/yyyy");
            String pago = databr.format(new Date());
            b.setPago(pago);
            BoletoDAO dao = new BoletoDAO();
            CDate conv = new CDate();
            if (dao.update(b)) {
                Date dado = conv.DataPTBRStringToDate(b.getPago());
                jTable1.setValueAt(dado, index, 4);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar gravar no banco de dados! Boleto ainda consta como não pago.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar salvar!\n" + ex.getMessage());
        }
        valorTotalEmAbertotxt.setText(Double.toString(totalEmAberto()));
        valorEmAbertoTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        datatxt = new javax.swing.JFormattedTextField();
        data2txt = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CheckBoxPagos = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cd_barras_leitor = new javax.swing.JTextField();
        atualizar_info_btn = new javax.swing.JButton();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        vencimento_boleto_txt = new javax.swing.JFormattedTextField();
        lancar_boleto_btn = new javax.swing.JButton();
        valor_boleto_txt = new javax.swing.JTextField();
        bancotxt = new javax.swing.JTextField();
        buscar_fornecedor_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        valorTotalEmAbertotxt = new javax.swing.JTextField();
        valorAbertotxt = new javax.swing.JTextField();
        totalLinhas = new javax.swing.JLabel();
        totalLinhasAberto = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciador de Boletos");

        jScrollPane1.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequencia", "Vencimento", "Fornecedor", "Valor", "Pago", "Código de Barras", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.util.Date.class, java.lang.Object.class, java.lang.Double.class, java.util.Date.class, java.lang.Object.class,java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(80);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(80);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(6).setMinWidth(40);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        try {
            datatxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datatxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datatxt.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        datatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datatxtKeyPressed(evt);
            }
        });

        try {
            data2txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data2txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data2txt.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        data2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data2txtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Data Inicial");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("Data Final");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        CheckBoxPagos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckBoxPagos.setText("Pagos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(data2txt)
            .addComponent(datatxt, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(CheckBoxPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(CheckBoxPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(datatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(data2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Lançar Boleto"));

        cd_barras_leitor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_barras_leitor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cd_barras_leitor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cd_barras_leitorKeyPressed(evt);
            }
        });

        atualizar_info_btn.setBackground(new java.awt.Color(0, 0, 0));
        atualizar_info_btn.setText("Atualizar");
        atualizar_info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_info_btnActionPerformed(evt);
            }
        });

        jComboBoxFornecedor.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxFornecedor.setMaximumRowCount(1000);
        jComboBoxFornecedor.setToolTipText("");

        try {
            vencimento_boleto_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vencimento_boleto_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vencimento_boleto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vencimento_boleto_txtKeyPressed(evt);
            }
        });

        lancar_boleto_btn.setBackground(new java.awt.Color(0, 0, 0));
        lancar_boleto_btn.setText("Lançar");
        lancar_boleto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancar_boleto_btnActionPerformed(evt);
            }
        });

        valor_boleto_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor_boleto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valor_boleto_txtKeyPressed(evt);
            }
        });

        bancotxt.setEditable(false);

        buscar_fornecedor_btn.setBackground(new java.awt.Color(0, 0, 0));
        buscar_fornecedor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        buscar_fornecedor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_fornecedor_btnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Código de Barras");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fornecedor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Banco");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vencimento");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cd_barras_leitor)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar_fornecedor_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizar_info_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bancotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vencimento_boleto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor_boleto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lancar_boleto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cd_barras_leitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizar_info_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscar_fornecedor_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bancotxt)
                    .addComponent(lancar_boleto_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vencimento_boleto_txt)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valor_boleto_txt))))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Baixar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Selecionado(s)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Alterar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TOTAL em aberto");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Em aberto na tabela");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        valorTotalEmAbertotxt.setEditable(false);
        valorTotalEmAbertotxt.setBackground(new java.awt.Color(255, 255, 255));
        valorTotalEmAbertotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorTotalEmAbertotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorTotalEmAbertotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTotalEmAbertotxtActionPerformed(evt);
            }
        });

        valorAbertotxt.setEditable(false);
        valorAbertotxt.setBackground(new java.awt.Color(255, 255, 255));
        valorAbertotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorAbertotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalLinhas.setText("Total de Linhas Exibidas: ");

        totalLinhasAberto.setText("Total de Linhas em Aberto: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorTotalEmAbertotxt)
                            .addComponent(valorAbertotxt)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalLinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(totalLinhasAberto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(valorTotalEmAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(valorAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLinhas)
                            .addComponent(totalLinhasAberto))))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel boletosTable = (DefaultTableModel) jTable1.getModel();
        boletosTable.setRowCount(0);
        BoletoDAO dao = new BoletoDAO();
        CDate conv = new CDate();
        List<Boleto> boletos = dao.findAll();
        String nome, cd_barras;
        Date vencimento_ = null, pago_;
        int id;
        double valor;
        
        Date ini = null, fim = null;
        if (data2txt.getText().equals("  /  /    ")) {
            data2txt.setText(datatxt.getText());
        }
        try {
            ini = conv.DataPTBRStringToDate(datatxt.getText());
        } catch (Exception ex) {
            System.out.println("Boleto--> Botao Filtro Atualizar--> Sem data inicial");
        }
        try {
            fim = conv.DataPTBRStringToDate(data2txt.getText());
        } catch (Exception ex) {
            System.out.println("Boleto--> Botao Filtro Atualizar--> Sem data final");
        }
        
        for (int i = 0; i < boletos.size(); i++) {
            id = boletos.get(i).getId();
            try {
                vencimento_ = conv.DataPTBRStringToDate(DataMySQLtoDataStringPT(boletos.get(i).getVencimento()));
            } catch (Exception ex) {
                Logger.getLogger(BoletoFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
            nome = boletos.get(i).getFornecedor_id().getNome();
            valor = boletos.get(i).getValor();
            valor = CDbl.CDblDuasCasas(valor);
            try {
                pago_ = conv.DataPTBRStringToDate(DataMySQLtoDataStringPT(boletos.get(i).getPago()));
            } catch (Exception ex) {
                pago_ = null;
            }
            cd_barras = boletos.get(i).getCd_barras();
            Object[] dados = {id, vencimento_, nome, valor, pago_, cd_barras, null};
            Date dboleto = null;
            try {
                dboleto = conv.DataMYSQLtoDate(boletos.get(i).getVencimento());
            } catch (Exception ex) {
                Logger.getLogger(BoletoFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
            if ("  /  /    ".equals(datatxt.getText())) {
                if (CheckBoxPagos.isSelected()) {
                    boletosTable.addRow(dados);
                } else if (pago_ == null) {
                    boletosTable.addRow(dados);
                }
            } else if (dboleto.compareTo(ini) >= 0 && dboleto.compareTo(fim) <= 0) {
                if (CheckBoxPagos.isSelected()) {
                    boletosTable.addRow(dados);
                } else if (pago_ == null) {
                    boletosTable.addRow(dados);
                }
            }
//            else if (datatxt.getText().equals(DataMySQLtoDataStringPT(boletos.get(i).getVencimento()))) {
//                boletosTable.addRow(dados);
//            }
        }
        valorEmAbertoTabela();
        totalLinhas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            if (jTable1.getValueAt(x, 6) == "X") {
                int id = (int) jTable1.getValueAt(x, 0);
                pagar(id, x);
                jTable1.setValueAt(null, x, 6);
            }
        }
        totalLinhas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int op = -1;
        op = JOptionPane.showOptionDialog(null, "Deseja dar baixa em todos os Boletos em aberto exibidos nessa tabela?", "Baixar Todos os Boletos", 1, op, frameIcon, null, null);
        if (op == 0) {
            int id;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                id = (int) jTable1.getValueAt(i, 0);
                pagar(id, i);
            }
        }
        totalLinhas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 6) == null) {
            jTable1.setValueAt("X", jTable1.getSelectedRow(), 6);
        } else {
            jTable1.setValueAt(null, jTable1.getSelectedRow(), 6);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() >= 0) {
            int id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            String data = new SimpleDateFormat("dd/MM/yyyy").format(jTable1.getValueAt(jTable1.getSelectedRow(), 1));
            String fornecedor = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2);
            String cd = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 5);
            double valor = (double) jTable1.getValueAt(jTable1.getSelectedRow(), 3);
            BoletoAtualizarFrm atualizar = new BoletoAtualizarFrm(id, data, valor, cd, fornecedor);
            atualizar.setVisible(true);
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() >= 0) {
            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
            int seq = (int) tb.getValueAt(jTable1.getSelectedRow(), 0);
            int op = -1;
            op = JOptionPane.showOptionDialog(null, "Deseja realmente excluir o boleto selecionado?", "Excluir Boleto", 1, op, frameIcon, null, null);
            if (op != 0) {
                return;
            }
            if (new BoletoDAO().delete(seq)) {
                JOptionPane.showMessageDialog(null, "Removido com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar remover o boleto do Banco de Dados!");
            }
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void datatxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datatxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_datatxtKeyPressed

    private void cd_barras_leitorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cd_barras_leitorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizar_info_btnActionPerformed(null);
        }
    }//GEN-LAST:event_cd_barras_leitorKeyPressed

    private void atualizar_info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_info_btnActionPerformed
        // TODO add your handling code here:
        if (!cd_barras_leitor.getText().equals("") && (cd_barras_leitor.getText().length() != 44 && cd_barras_leitor.getText().length() != 47)) {
            JOptionPane.showMessageDialog(null, "Cógido de barras inválido! Verifique se o código de barras esta foi escaneado/digitado corretamente.");
            cd_barras_leitor.setText("");
            return;
        } else if (cd_barras_leitor.getText().length() == 47) {
            String temp = "";
            temp = temp + cd_barras_leitor.getText().substring(0, 4);
            temp = temp + cd_barras_leitor.getText().substring(32);
            temp = temp + cd_barras_leitor.getText().substring(4, 9);
            temp = temp + cd_barras_leitor.getText().substring(10, 20);
            temp = temp + cd_barras_leitor.getText().substring(21, 31);
            if (temp.length() == 44) {
                cd_barras_leitor.setText(temp);
            } else {
                JOptionPane.showMessageDialog(null, "Algo deu errado ao tentar converter o código de barras manual.");
                return;
            }
        }
        setbanco(Integer.parseInt(cd_barras_leitor.getText().substring(0, 3)));
        atualizarFornecedor(getbanco(), cd_barras_leitor.getText());
        if (jComboBoxFornecedor.getItemCount() == 0) {
            String provavel = cd_barras_leitor.getText().substring(25, 29);
            //JOptionPane.showMessageDialog(null, "Fornecedor nao cadastrado ou não atualizado:\nProvável numero do fornecedor: " + provavel + "\nBanco: " + getbanco());
            Fornecedor_ListaBancoJD jd = new Fornecedor_ListaBancoJD(null, true, getbanco());
            jd.setVisible(true);
            if (jd.desc != null) {
                jComboBoxFornecedor.removeAllItems();
                jComboBoxFornecedor.addItem(jd.desc);
            } else {
                return;
            }
        }
        bancotxt.setText(Integer.toString(getbanco()));
        vencimento_boleto_txt.setText(Cdate(Integer.parseInt(cd_barras_leitor.getText().substring(5, 9))));
        if (vencimento_boleto_txt.getText().equals("07/10/1997")) {
            jLabel10.setIcon(new ImageIcon(getClass().getResource("/Imagens/exclamation.png")));
        } else {
            jLabel10.setIcon(new ImageIcon(getClass().getResource("/Imagens/flag_green.png")));
        }
        valor_boleto_txt.setText(Double.toString(Double.parseDouble(cd_barras_leitor.getText().substring(9, 19)) / 100));
    }//GEN-LAST:event_atualizar_info_btnActionPerformed

    private void vencimento_boleto_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vencimento_boleto_txtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            valor_boleto_txt.requestFocus();
        }
    }//GEN-LAST:event_vencimento_boleto_txtKeyPressed

    private void lancar_boleto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancar_boleto_btnActionPerformed
        // TODO add your handling code here:
        Boleto b_temp = null;
        try {
            if (vencimento_boleto_txt.getText().equals("07/10/1997")) {
                jLabel10.setIcon(new ImageIcon(getClass().getResource("/Imagens/exclamation.png")));
                throw new Exception("Provável vencimento inválido!");
            }
            jLabel10.setIcon(new ImageIcon(getClass().getResource("/Imagens/flag_green.png")));
            Boleto boleto = new Boleto();
            Fornecedor fornecedor = new Fornecedor();
            FornecedorDAO dao = new FornecedorDAO();
            for (Fornecedor f : dao.findAll()) {
                if (f.getBanco() == getbanco() && f.getNome().equals(jComboBoxFornecedor.getItemAt(jComboBoxFornecedor.getSelectedIndex()))) {
                    fornecedor.setNome(f.getNome());
                    fornecedor.setBanco(f.getBanco());
                    fornecedor.setId(f.getId());
                }
            }
            boleto.setCd_barras(cd_barras_leitor.getText());
            boleto.setFornecedor_id(fornecedor);
            String value;
            value = valor_boleto_txt.getText().replaceAll(",", ".");
            boleto.setValor(Double.parseDouble(value));
            boleto.setVencimento(vencimento_boleto_txt.getText());
            BoletoDAO bdao = new BoletoDAO();
            for (Boleto b : bdao.findAll()) {
                if (b.getCd_barras().equals(boleto.getCd_barras())) {
                    //throw new Exception("Boleto já lançado!");
                    int op = -1;
                    op = JOptionPane.showOptionDialog(null, "Um boleto com o mesmo código de barras já se encontra lançado,\ndeseja continuar?", "Cógido já existente!", 1, op, frameIcon, null, null);
                    if (op != 0) {
                        return;
                    }
                }
            }
            bdao.reconect();
            if (bdao.save(boleto)) {
                b_temp = boleto;
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar! " + ex.getMessage());
        } finally {
            cd_barras_leitor.setText("");
            vencimento_boleto_txt.setText("");
            valor_boleto_txt.setText("");
            jComboBoxFornecedor.removeAllItems();
            if (b_temp != null) {
                acaoLancarAtualizarBtn(b_temp);
            } else {
                acaoLancarAtualizarBtn();
            }
            cd_barras_leitor.requestFocus();
        }
    }//GEN-LAST:event_lancar_boleto_btnActionPerformed

    private void valor_boleto_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_boleto_txtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lancar_boleto_btn.requestFocus();
        }
    }//GEN-LAST:event_valor_boleto_txtKeyPressed

    private void buscar_fornecedor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_fornecedor_btnActionPerformed
        // TODO add your handling code here:
        Fornecedor_ListaBancoJD dj = new Fornecedor_ListaBancoJD(null, true, getbanco());
        dj.setVisible(true);
        if (dj.desc != null) {
            jComboBoxFornecedor.removeAllItems();
            jComboBoxFornecedor.addItem(dj.desc);
        }
    }//GEN-LAST:event_buscar_fornecedor_btnActionPerformed

    private void valorTotalEmAbertotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalEmAbertotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTotalEmAbertotxtActionPerformed

    private void data2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data2txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxPagos;
    private javax.swing.JButton atualizar_info_btn;
    private javax.swing.JTextField bancotxt;
    private javax.swing.JButton buscar_fornecedor_btn;
    private javax.swing.JTextField cd_barras_leitor;
    private javax.swing.JFormattedTextField data2txt;
    private javax.swing.JFormattedTextField datatxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lancar_boleto_btn;
    private javax.swing.JLabel totalLinhas;
    private javax.swing.JLabel totalLinhasAberto;
    private javax.swing.JTextField valorAbertotxt;
    private javax.swing.JTextField valorTotalEmAbertotxt;
    private javax.swing.JTextField valor_boleto_txt;
    private javax.swing.JFormattedTextField vencimento_boleto_txt;
    // End of variables declaration//GEN-END:variables
    public void atualizarFornecedor(int banco, String cd_barras) {
        List<Fornecedor> fornecedores = new FornecedorDAO().findAll();
        List<Fornecedor> atualizado = new ArrayList<>();
        jComboBoxFornecedor.removeAllItems();
        System.out.println("Combobox sem ordenar::");
        for (Fornecedor f : fornecedores) {
            if (f.getNumero() != null) {
                if (f.getBanco() == banco && cd_barras.contains(f.getNumero())) {
                    atualizado.add(f);
                    System.out.println(f.getNome());
                }
            }
        }
        atualizado.sort((t, t1) -> {
            if (t.getNumero().length() > t1.getNumero().length()) {
                return -1;
            }
            if (t.getNumero().length() < t1.getNumero().length()) {
                return 1;
            }
            return 0;
        });
        System.out.println("Combobox ordenado::");
        for (Fornecedor f : atualizado) {
            jComboBoxFornecedor.addItem(f.getNome());
            System.out.println(f.getNome());
        }
    }
    
    public String Cdate(int temp) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dataInicial=null;
        try {
            dataInicial = formato.parse("07/10/1997");
        } catch (ParseException ex) {
        }
        Calendar calendarData = Calendar.getInstance();
        calendarData.setTime(dataInicial);
        int somar = temp;
        calendarData.add(Calendar.DATE, somar);
        Date vencimento = calendarData.getTime();
        return formato.format(vencimento);
    }
    
    public void acaoLancarAtualizarBtn() {
        datatxt.setText("");
        data2txt.setText("");
        jButton1ActionPerformed(null);
        jTable1.setRowSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);
        setPosicaoViewPort((JViewport) jTable1.getParent(), jTable1.getCellRect(jTable1.getRowCount() - 1, 0, true));
    }
    
    public void acaoLancarAtualizarBtn(Boleto b) {
        datatxt.setText("");
        data2txt.setText("");
        jButton1ActionPerformed(null);
        
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            String codigo = (String) jTable1.getValueAt(x, 5);
            if (codigo.equals(b.getCd_barras())) {
                jTable1.setRowSelectionInterval(x, x);
                setPosicaoViewPort((JViewport) jTable1.getParent(), jTable1.getCellRect(x, 0, true));
                break;
            }
        }
        
    }
    
    private void setPosicaoViewPort(JViewport viewport, Rectangle posicao) {
        Point ponto = viewport.getViewPosition();
        posicao.setLocation(posicao.x - ponto.x, posicao.y - ponto.y);
        viewport.scrollRectToVisible(posicao);
    }
    
    public String colocarPonto(String s) {
        int index = s.indexOf(",");
        if (index > 3) {
            String sub = s.substring(0, index);
            int controle = 0;
            String temp = "";
            for (int x = 0; x < index + 1; x++) {
                if (x == index - 3) {
                    temp += '.';
                } else {
                    temp += sub.charAt(controle);
                    controle++;
                }
            }
            temp += s.substring(index);
            s = temp;
        }
        return s;
    }
    
    public int getbanco() {
        return this.banco;
    }
    
    public void setbanco(int banco_) {
        this.banco = banco_;
    }
    
    public double totalEmAberto() {
        double soma = 0.0;
        BoletoDAO dao = new BoletoDAO();
        for (Boleto b : dao.findAll()) {
            if (b.getPago() == null) {
                soma += b.getValor();
            }
        }
        return CDbl.CDblDuasCasas(soma);
    }
    
    private void valorEmAbertoTabela() {
        double valorTemp = 0;
        try {
            for (int x = 0; x < jTable1.getRowCount(); x++) {
                if (jTable1.getValueAt(x, 4) == null) {
                    valorTemp += Double.parseDouble(jTable1.getValueAt(x, 3).toString());
                }
            }
        } catch (Exception ex) {
            System.err.println("Erro ao tentar alocar valor na label 'valorAbertotxt': " + ex.getMessage());
            valorTemp = 0;
        }
        String valorString = (Double.toString(CDbl.CDblDuasCasas(valorTemp)));
        valorString = valorString.replaceAll("\\.", ",");
        valorString = colocarPonto(valorString);
        valorAbertotxt.setText(valorString);
        
    }
    
    public long diasRestantes(String data) throws Exception {
        CDate conv = new CDate();
        return conv.diasRestantes(data);
    }
    
    private void atualizarValorTotalAberto() {
        String valorString = Double.toString(totalEmAberto());
        valorString = valorString.replaceAll("\\.", ",");
        valorString = colocarPonto(valorString);
        valorTotalEmAbertotxt.setText(valorString);
    }
    
    private void totalLinhas(){
        int aberto =0;
        for (int x=0;x<jTable1.getRowCount();x++){
            if (jTable1.getValueAt(x, 4) == null){
                aberto++;
            }
        }
        totalLinhas.setText("Total de Linhas Exibidas: "+Integer.toString(jTable1.getRowCount()));
        totalLinhasAberto.setText("Total de Linhas em Aberto: "+Integer.toString(aberto));
    }
}
