/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Boleto.Form;

import funcoes.AutoCompletion;
import funcoes.CDate;
import funcoes.CDbl;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.ChequeDAO;
import model.DAO.FornecedorDAO;
import model.bean.Cheque;
import model.bean.Fornecedor;

/**
 *
 * @author User
 */
public class ChequeFrm extends javax.swing.JInternalFrame {

    private DefaultTableModel tb;
    private List<Cheque> cheques;
    private List<Fornecedor> fornecedores;

    /**
     * Creates new form TelaChequeVisualizar
     */
    public ChequeFrm() {
        initComponents();
        //pc do samoel dando erro nesse metodo
//        try {
//            this.setMaximum(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(ChequeFrm.class.getName()).log(Level.SEVERE, null, ex);
//        }
        tb = (DefaultTableModel) jTable1.getModel();
        AutoCompletion.enable(jComboBox1);
        jTable1.setRowSorter(new TableRowSorter<>(tb));
        cheques = new ChequeDAO().findAll();
        fornecedores = new FornecedorDAO().findAll();
        buscarTodosBtnActionPerformed(null);
        atualizarValorEmAberto();
        atualizarFornecedor();
    }

    private void atualizartable(int op) {
        tb.setRowCount(0);
        long seq;
        String fornecedor;
        Date vencimento = null, emissao = null, pago = null;
        double valor;
        cheques = new ChequeDAO().findAll();
        for (Cheque cheque : cheques) {
            seq = cheque.getSeq();
            try {
                emissao = CDate.MYSQLtoDate(cheque.getEmissao());
            } catch (Exception ex) {
                emissao = null;
            }
            try {
                vencimento = CDate.MYSQLtoDate(cheque.getPredatado());
            } catch (Exception ex) {
                vencimento = null;
            }
            try {
                pago = CDate.MYSQLtoDate(cheque.getSaque());
            } catch (Exception ex) {
                pago = null;
            }
            fornecedor = cheque.getFornecedor().getNome();
            valor = cheque.getValor();
            Object[] dados = {seq, emissao, vencimento, fornecedor, valor, pago};
            switch (op) {
                case 1:
                    tb.addRow(dados);
                    break;
                case 2:
                    if (pago == null && valor != 0) {
                        tb.addRow(dados);
                    }
                    break;
                case 3:
                    if (pago != null && valor != 0) {
                        tb.addRow(dados);
                    }
                    break;
                case 4:
                    if (pago == null & valor == 0) {
                        tb.addRow(dados);
                    }
                    break;
                case 5:
                    if (seq == Integer.parseInt(seqtxt.getText())) {
                        tb.addRow(dados);
                    }
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        seqtxt = new javax.swing.JTextField();
        buscarSequenciaBtn = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        buscarTodosBtn = new javax.swing.JButton();
        buscarEmAbertoBtn = new javax.swing.JButton();
        buscarPagosBtn = new javax.swing.JButton();
        buscarNulosBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nulobtn = new javax.swing.JButton();
        proximoBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        atualizarFornecedoresBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seqtxt1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        emissaotxt = new javax.swing.JFormattedTextField();
        predatadotxt = new javax.swing.JFormattedTextField();
        valortxt = new javax.swing.JTextField();
        valorEmAbertotxt = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciador de Cheques");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequencia", "Emissao", "Vencimento", "Fornecedor", "Valor", "Saque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.util.Date.class, java.util.Date.class, java.lang.Object.class, java.lang.Double.class, java.util.Date.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buscarSequenciaBtn.setBackground(new java.awt.Color(0, 0, 0));
        buscarSequenciaBtn.setText("Buscar");
        buscarSequenciaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarSequenciaBtnActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sequência");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        buscarTodosBtn.setBackground(new java.awt.Color(0, 0, 0));
        buscarTodosBtn.setText("Todos");
        buscarTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTodosBtnActionPerformed(evt);
            }
        });

        buscarEmAbertoBtn.setBackground(new java.awt.Color(0, 0, 0));
        buscarEmAbertoBtn.setText("Em Aberto");
        buscarEmAbertoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmAbertoBtnActionPerformed(evt);
            }
        });

        buscarPagosBtn.setBackground(new java.awt.Color(0, 0, 0));
        buscarPagosBtn.setText("Pagos");
        buscarPagosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPagosBtnActionPerformed(evt);
            }
        });

        buscarNulosBtn.setBackground(new java.awt.Color(0, 0, 0));
        buscarNulosBtn.setText("Nulos");
        buscarNulosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNulosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscarTodosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(buscarPagosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarEmAbertoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscarNulosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seqtxt))
                        .addGap(0, 0, 0)
                        .addComponent(buscarSequenciaBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buscarSequenciaBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seqtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarTodosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEmAbertoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarNulosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPagosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total em Aberto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Lançar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Emissão");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pré-datado");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        nulobtn.setBackground(new java.awt.Color(255, 255, 255));
        nulobtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nulobtn.setText("Nulo");
        nulobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nulobtnActionPerformed(evt);
            }
        });

        proximoBtn.setBackground(new java.awt.Color(255, 255, 255));
        proximoBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        proximoBtn.setText("Próximo");
        proximoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoBtnActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fornecedor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        atualizarFornecedoresBtn.setBackground(new java.awt.Color(0, 0, 0));
        atualizarFornecedoresBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_refresh.png"))); // NOI18N
        atualizarFornecedoresBtn.setToolTipText("Atualizar Fornecedores");
        atualizarFornecedoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarFornecedoresBtnActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sequência");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        seqtxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seqtxt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                seqtxt1FocusLost(evt);
            }
        });

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        try {
            emissaotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        emissaotxt.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        emissaotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emissaotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emissaotxtKeyPressed(evt);
            }
        });

        try {
            predatadotxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        predatadotxt.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        predatadotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        valortxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valortxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valortxtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nulobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proximoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seqtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atualizarFornecedoresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emissaotxt)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(predatadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(valortxt))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(seqtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atualizarFornecedoresBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emissaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predatadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(valortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nulobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proximoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        valorEmAbertotxt.setEditable(false);
        valorEmAbertotxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(valorEmAbertotxt))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorEmAbertotxt))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTodosBtnActionPerformed
        atualizartable(1);
    }//GEN-LAST:event_buscarTodosBtnActionPerformed

    private void buscarEmAbertoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmAbertoBtnActionPerformed
        atualizartable(2);
    }//GEN-LAST:event_buscarEmAbertoBtnActionPerformed

    private void buscarPagosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPagosBtnActionPerformed
        atualizartable(3);
    }//GEN-LAST:event_buscarPagosBtnActionPerformed

    private void buscarNulosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNulosBtnActionPerformed
        atualizartable(4);
    }//GEN-LAST:event_buscarNulosBtnActionPerformed

    private void buscarSequenciaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarSequenciaBtnActionPerformed
        if (!"".equals(seqtxt.getText())) {
            atualizartable(5);
        }
    }//GEN-LAST:event_buscarSequenciaBtnActionPerformed

    private void seqtxt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_seqtxt1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_seqtxt1FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void nulobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nulobtnActionPerformed
        if (!seqtxt1.getText().equals("")) {
            Fornecedor fornecedor = new Fornecedor();
            fornecedor.setId(1);
            Cheque cheque = new Cheque(Integer.parseInt(seqtxt1.getText()), fornecedor, "00/00/0000", "00/00/0000", 0);
            ChequeDAO dao = new ChequeDAO();
            if (dao.anular(cheque)) {
                seqtxt1.setText(String.valueOf(Integer.parseInt(seqtxt1.getText()) + 1));
                atualizartable(4);
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao anular cheque no banco de dados!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informe a sequencia do cheque a ser anulado.");
        }
    }//GEN-LAST:event_nulobtnActionPerformed

    private void proximoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoBtnActionPerformed
        /*
        *Caso o campo de numero esteja vazio, obtem o maior numero de cheque ja lançado e incrementa em 1 e retorna
         */
        if (seqtxt1.getText().equals("")) {
            int max = 0;
            for (Cheque c : new ChequeDAO().findAll()) {
                if (c.getSeq() > max) {
                    max = c.getSeq();
                }
            }
            max++;
            seqtxt1.setText(Integer.toString(max));
            return;
        }
        /*
        *verifica se ja existe algum cheque com o mesmo numero lançado, caso sim da opção de atualizar o cheque.
         */
        boolean chequeExiste = false;
        for (Cheque c : new ChequeDAO().findAll()) {
            if (c.getSeq() == Integer.parseInt(seqtxt1.getText())) {
                int op = JOptionPane.showOptionDialog(null, "Cheque ja lançado, deseja atualizar as informações desse cheque?", "Cheque ja lançado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, frameIcon, null, null);
                if (op != JOptionPane.YES_OPTION) {
                    return;
                }
                chequeExiste = true;
            }
        }
        try {
            Fornecedor fornecedor = new Fornecedor();
            for (Fornecedor f : new FornecedorDAO().findAll()) {
                if (f.getNome().equals(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()))) {
                    fornecedor.setId(f.getId());
                }
            }
            if (predatadotxt.getText().equals("  /  /    ")) {          //iguala datas caso o campo prédatado esteja vazio.
                predatadotxt.setText(emissaotxt.getText());
            }
            double valor = Double.parseDouble(valortxt.getText().replaceAll(",", "."));
            Cheque cheque = new Cheque(Integer.parseInt(seqtxt1.getText()), fornecedor, emissaotxt.getText(), predatadotxt.getText(), valor);
            if (!chequeExiste) {
                if (new ChequeDAO().save(cheque)) {
                    seqtxt1.setText(String.valueOf(Integer.parseInt(seqtxt1.getText()) + 1));
                } else {
                    throw new Exception("Falha ao salvar cheque!");
                }
            } else {
                if (new ChequeDAO().update(cheque)) {
                    seqtxt1.setText(String.valueOf(Integer.parseInt(seqtxt1.getText()) + 1));
                } else {
                    throw new Exception("Falha ao atualizar cheque!");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Algo deu errado: " + ex.getMessage());
        } finally {
            limpartxt();
            atualizartable(2);
        }
    }//GEN-LAST:event_proximoBtnActionPerformed

    private void atualizarFornecedoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarFornecedoresBtnActionPerformed
        atualizarFornecedor();
        jComboBox1.requestFocus();
    }//GEN-LAST:event_atualizarFornecedoresBtnActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emissaotxt.requestFocus();
        }

    }//GEN-LAST:event_jComboBox1KeyPressed

    private void emissaotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emissaotxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            valortxt.requestFocus();
        }
    }//GEN-LAST:event_emissaotxtKeyPressed

    private void valortxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valortxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            proximoBtn.requestFocus();
        }
    }//GEN-LAST:event_valortxtKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getRowCount() >= 0 && evt.getClickCount() == 2) {
            if (!"NULO".equals((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3))) {
                long seq = (long) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                for (Cheque cheque : new ChequeDAO().findAll()) {
                    if (seq == cheque.getSeq()) {
                        BaixarChequeJD ch = new BaixarChequeJD(null, true, cheque);
                        ch.setVisible(true);
                        if (ch.concluido) {
                            tb.removeRow(jTable1.getSelectedRow());
                            atualizarValorEmAberto();
                            totalEmAberto();
                        }
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarFornecedoresBtn;
    private javax.swing.JButton buscarEmAbertoBtn;
    private javax.swing.JButton buscarNulosBtn;
    private javax.swing.JButton buscarPagosBtn;
    private javax.swing.JButton buscarSequenciaBtn;
    private javax.swing.JButton buscarTodosBtn;
    private javax.swing.JFormattedTextField emissaotxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nulobtn;
    private javax.swing.JFormattedTextField predatadotxt;
    private javax.swing.JButton proximoBtn;
    private javax.swing.JTextField seqtxt;
    private javax.swing.JTextField seqtxt1;
    private javax.swing.JTextField valorEmAbertotxt;
    private javax.swing.JTextField valortxt;
    // End of variables declaration//GEN-END:variables

    public void atualizarValorEmAberto() {
        valorEmAbertotxt.setText("R$ " + colocarPonto(Double.toString(totalEmAberto()).replaceAll("\\.", ",")));
    }

    public String colocarPonto(String s) {
        int index = s.indexOf(",");
        if (index > 3) {
            String sub = s.substring(0, index);
            int controle = 0;
            String temp = "";
            for (int x = 0; x < index + 1; x++) {
                if (x == index - 3) {
                    temp += '.';
                } else {
                    temp += sub.charAt(controle);
                    controle++;
                }
            }
            temp += s.substring(index);
            s = temp;
        }
        return s;
    }

    public double totalEmAberto() {
        double soma = 0;
        for (Cheque c : new ChequeDAO().findAll()) {
            if (c.getSaque() == null) {
                soma += c.getValor();
            }
        }
        return CDbl.CDblDuasCasas(soma);
    }

    private void limpartxt() {
        emissaotxt.setText("");
        predatadotxt.setText("");
        valortxt.setText("");
        jComboBox1.requestFocus();
    }

    private void atualizarFornecedor() {
        jComboBox1.removeAllItems();
        FornecedorDAO dao = new FornecedorDAO();
        for (Fornecedor f : dao.findAll()) {
            if (f.getBanco() == -1) {
                jComboBox1.addItem(f.getNome());
            }
        }
    }
}
